### ISSUE TITLE
ASP.NET Core 

### ISSUE THREAD

**Issue by AndrewKralovec** [cillierscharl/forecast.io-csharp#33]
I am a Linux Debian user. I was wondering if there was a way i could use this library for ASP.NET Core. If so, how ?

**Comment by amweiss** [comment]
I had a similar question, but wrote a quick netstandard library that works for .NET Core or any of the Windows platforms: https://github.com/amweiss/dark-sky-core.

More than happy to contribute back to this project if it makes sense.

**Comment by cillierscharl** [comment]
Added.
