### ISSUE TITLE
how to access response.daily.tempertureMax

### ISSUE THREAD

**Issue by F4u5t** [cillierscharl/forecast.io-csharp#42]
All I can see in response.daily    is **data**, **summary** and **icon**
How do I access the data items like temperatureMax?

**Comment by cillierscharl** [comment]
Should be under Data https://github.com/cillierscharl/forecast.io-csharp/blob/7a8b3d22fadd18b580ef789cf38464137009d296/forecast.io-standard/Entities/ForecastIOResponse.cs#L90
